# Generated by Django 3.1.7 on 2021-02-23 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(help_text='Enter department name', max_length=50)),
                ('dep_description', models.CharField(help_text='Enter department description', max_length=200)),
            ],
            options={
                'ordering': ['dep_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, help_text='Unique User ID', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter username', max_length=30)),
                ('password', models.CharField(help_text='Enter password', max_length=30)),
                ('company_email', models.EmailField(help_text='Enter company email', max_length=254)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=30)),
                ('middle_name', models.CharField(help_text='Enter your middle name', max_length=30)),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=30)),
                ('date_of_birth', models.DateField(help_text='Enter your birthday')),
                ('phone_number', models.CharField(help_text='Enter your phone number', max_length=13)),
                ('address', models.CharField(help_text='Enter your address', max_length=100)),
                ('personal_email', models.EmailField(help_text='Enter personal email', max_length=254)),
                ('join_date', models.DateField()),
                ('quit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('w', 'Working'), ('i', 'Intern'), ('t', 'Temporarily off'), ('q', 'Quit job')], default='w', help_text='Employee status', max_length=1)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.department')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.user')),
            ],
            options={
                'ordering': ['first_name', 'department'],
            },
        ),
    ]
