# Generated by Django 3.1.7 on 2021-02-24 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0002_auto_20210223_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_description',
            field=models.CharField(blank=True, help_text='Enter department description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, help_text='Enter your address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Enter personal email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique User ID', primary_key=True, serialize=False),
        ),
    ]
