# Generated by Django 3.1.7 on 2021-02-24 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0003_auto_20210224_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(help_text='Enter position name', max_length=50)),
                ('pos_description', models.CharField(blank=True, help_text='Enter position description', max_length=200, null=True)),
            ],
            options={
                'ordering': ['position_name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, help_text='Enter employee salary', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, help_text='Enter employee address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(help_text='Enter employee birthday'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Select department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(help_text='Enter employee first name', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text='Enter employee last name', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(help_text='Enter employee middle name', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Enter employee personal email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter employee phone number', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.ForeignKey(blank=True, help_text='Select username', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.user'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Select position', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.position'),
        ),
    ]
