# Generated by Django 3.1.7 on 2021-02-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0005_auto_20210224_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary_currency',
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
