# Generated by Django 3.1.7 on 2021-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0007_auto_20210224_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sex_status',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('n', 'None')], default='n', help_text='Sex', max_length=1),
        ),
    ]
