# Generated by Django 3.1.7 on 2021-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0008_employee_sex_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sex_status',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default='n', help_text='Sex', max_length=1),
        ),
    ]
