# Generated by Django 3.1.7 on 2021-03-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0009_auto_20210228_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image_url',
            field=models.CharField(blank=True, help_text='Enter image location', max_length=300, null=True),
        ),
    ]
